apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: quarkus
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: my-cluster 
spec:
  authentication:
    type: tls 
  authorization:
    type: simple
    acls: 
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
