{{- range .Values.external_app_list }}
{{- $parts := split "_" . }}
apiVersion: v1
kind: Service
metadata:
  name: ext-app-metric-{{ $parts._0}}
  labels:
    external-app-monitor: "true"
  namespace: external-service
spec:
  ports:
  - name: web
    port: {{ $parts._2 }}
    protocol: TCP
    targetPort: 8080
  selector: {}
  sessionAffinity: None
  type: ClusterIP
---
{{- end }}
