apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Values.namespace }}
spec:
  baseImage: quay.io/integreatly/grafana@sha256:174987125ca36f8de41184267d15b7a68c65c19be6979bfaa0b49f205f58f479
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: admin
      admin_user: admin
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  dataStorage:
    labels: # Additional labels for the PVC
      app: grafana
    annotations: # Additional annotations for the PVC
      app: grafana
    accessModes: # An array of access modes, e.g. `ReadWriteOnce`
    - ReadWriteMany
    size: '10Gi'        # Requested size, e.g. `10Gi`
    class: "nfs-client"
  ingress:
    enabled: true
    hostname: {{ .Values.nameOverride }}.{{ .Values.subdomain }}
