apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: infra
spec:
  machineConfigSelector:
    # matchLabels:
    #   machineconfiguration.openshift.io/role: infra
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - worker
        - infra
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/infra: ""
  paused: false
