apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  httpProxy: http://192.168.2.15:3128
  httpsProxy: http://192.168.2.15:3128
  noProxy: quay.io,registry.redhat.io,.svc,.cluster.local,master.ocp1.galaxy.io 
  readinessEndpoints:
  - http://www.google.com 
  - https://www.google.com
  # trustedCA:
  #   name: user-ca-bundle 
