apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: galaxy-grafana
  namespace: galaxy-grafana
spec:
  host: galaxy-grafana.apps-crc.testing
  port:
    targetPort: 3000
  tls:
    termination: edge
  to:
    kind: Service
    name: grafana-service
    weight: 100
  wildcardPolicy: None
