apiVersion: v1
kind: Service
metadata:
  labels:
    external-infra-monitor: "true"
  name: externalip-nuc1-todo-app
  namespace: external-service
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodeport: 0
  selector: {}
  sessionAffinity: None
  type: ClusterIP
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "externalip-nuc1-todo-app" 
subsets: 
  - addresses:
    - ip: "192.168.2.10" 
    ports:
      - port: 8080 
        name: "web"
